version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gbriche/oc-lettings-site:web
    command: gunicorn --bind 0.0.0.0:8000 oc_lettings_site.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: gbriche/oc-lettings-site:nginx
    ports:
      - "80:80"
    depends_on:
      - web
