# Images Locales
# Définir la variable localement : $env:GIT_SHA = git rev-parse --short HEAD

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_SHA: ${GIT_SHA}
    image: gbriche/oc-lettings-site:web-${GIT_SHA}
    command: gunicorn --bind 0.0.0.0:8000 oc_lettings_site.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: gbriche/oc-lettings-site:nginx-${GIT_SHA}
    ports:
      - "80:80"
    depends_on:
      - web
