version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 oc_lettings_site.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        NGINX_VERSION: 1.21
    ports:
      - "80:80"
    depends_on:
      - web
